/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FloorsSequenceImport } from './routes/floors/$sequence'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FloorsSequenceRoute = FloorsSequenceImport.update({
  id: '/floors/$sequence',
  path: '/floors/$sequence',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/floors/$sequence': {
      id: '/floors/$sequence'
      path: '/floors/$sequence'
      fullPath: '/floors/$sequence'
      preLoaderRoute: typeof FloorsSequenceImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/floors/$sequence': typeof FloorsSequenceRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/floors/$sequence': typeof FloorsSequenceRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/floors/$sequence': typeof FloorsSequenceRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/floors/$sequence'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/floors/$sequence'
  id: '__root__' | '/' | '/floors/$sequence'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FloorsSequenceRoute: typeof FloorsSequenceRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FloorsSequenceRoute: FloorsSequenceRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/floors/$sequence"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/floors/$sequence": {
      "filePath": "floors/$sequence.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
